export const PRACTICE_MULTIPLE_CHOICE_DEMO = {
    questions: [
        {
            id: '1',
            prompt: 'Theo Ăngghen, vấn đề cơ bản lớn của mọi triết học là gì?',
            options: [
                'Mối quan hệ giữa tư duy và tồn tại',
                'Nguồn gốc của loài người',
                'Cấu trúc của vật chất',
                'Sự phát triển của ngôn ngữ',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '2',
            prompt: 'Triết học xuất hiện vào khoảng thời gian nào?',
            options: [
                'Khoảng thế kỷ VIII - VI TCN',
                'Thời kỳ Phục Hưng',
                'Thế kỷ XIX',
                'Sau Công nguyên',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '3',
            prompt: 'Trung tâm hình thành triết học cổ đại gồm những nền văn minh nào?',
            options: [
                'Trung Quốc, Ấn Độ, Hy Lạp',
                'Ai Cập, La Mã, Pháp',
                'Nga, Đức, Mỹ',
                'Nhật Bản, Hàn Quốc, Việt Nam',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '4',
            prompt: 'Thuật ngữ “triết” trong Trung Quốc có nghĩa là gì?',
            options: [
                'Trí tuệ, hiểu biết sâu sắc',
                'Niềm tin tôn giáo',
                'Kỹ thuật canh tác',
                'Quản lý nhà nước',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '5',
            prompt: 'Darśana trong triết học Ấn Độ có nghĩa là gì?',
            options: [
                'Chiêm ngưỡng, suy ngẫm bằng lý trí',
                'Hành động theo bản năng',
                'Tập trung sản xuất',
                'Luyện tập thể chất',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '6',
            prompt: 'Philosophia trong triết học Hy Lạp có nghĩa là gì?',
            options: [
                'Yêu mến sự thông thái',
                'Sự chiến thắng của lý trí',
                'Tình yêu thiên nhiên',
                'Khả năng quan sát',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '7',
            prompt: 'Triết học thuộc hình thái nào của đời sống xã hội?',
            options: [
                'Hình thái ý thức xã hội',
                'Sản xuất vật chất',
                'Tổ chức chính trị',
                'Lĩnh vực kỹ thuật',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '8',
            prompt: 'Triết học nghiên cứu thế giới như thế nào?',
            options: [
                'Một chỉnh thể thống nhất',
                'Những mảnh rời rạc',
                'Các hiện tượng ngẫu nhiên',
                'Một chuỗi sự kiện ngắn hạn',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '9',
            prompt: 'Triết học tìm ra những quy luật nào?',
            options: [
                'Quy luật chung nhất chi phối tự nhiên, xã hội và tư duy',
                'Quy luật vật lý lượng tử',
                'Quy luật thị trường ngắn hạn',
                'Quy luật khí hậu vùng nhiệt đới',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '10',
            prompt: 'Triết học hệ thống hóa tri thức bằng gì?',
            options: [
                'Tư duy lý luận, logic và khoa học',
                'Cảm tính tức thời',
                'Kinh nghiệm cá nhân đơn lẻ',
                'Thói quen xã hội',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '11',
            prompt: 'Triết học phản ánh khả năng nào của con người?',
            options: [
                'Khả năng nhận thức và đánh giá thế giới',
                'Khả năng ghi nhớ máy móc',
                'Khả năng vận động cơ học',
                'Khả năng sinh tồn sinh học',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '12',
            prompt: 'Bản chất của triết học là gì?',
            options: [
                'Hoạt động tinh thần của con người',
                'Hoạt động sản xuất công nghiệp',
                'Kỹ thuật tính toán',
                'Thực hành tôn giáo',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '13',
            prompt: 'Triết học nhằm tìm hiểu điều gì của sự vật, hiện tượng?',
            options: [
                'Bản chất',
                'Màu sắc bề ngoài',
                'Số lượng chi tiết',
                'Kích thước vật lý',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '14',
            prompt: 'Triết học cổ đại phương Đông tiêu biểu ở đâu?',
            options: [
                'Trung Quốc và Ấn Độ',
                'Pháp và Đức',
                'Nga và Mỹ',
                'Ý và Tây Ban Nha',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '15',
            prompt: 'Triết học giúp con người hướng đến điều gì?',
            options: [
                'Chân lý và lẽ phải',
                'Lợi nhuận trước mắt',
                'Thói quen lặp lại',
                'Sự im lặng tuyệt đối',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '16',
            prompt: 'Triết học phản ánh điều gì của con người?',
            options: [
                'Khả năng nhận thức và đánh giá thế giới',
                'Khả năng tiêu thụ vật chất',
                'Khả năng lao động cơ bắp',
                'Khả năng di chuyển',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '17',
            prompt: 'Triết học là hoạt động gì của con người?',
            options: [
                'Hoạt động tinh thần',
                'Hoạt động thể thao',
                'Hoạt động thương mại',
                'Hoạt động cơ học',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '18',
            prompt: 'Triết học tìm bản chất của cái gì?',
            options: [
                'Sự vật, hiện tượng',
                'Màu sắc và âm thanh',
                'Mối quan hệ gia đình',
                'Kỹ năng vận động',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '19',
            prompt: 'Triết học gắn với nhu cầu nào của con người?',
            options: [
                'Tìm hiểu và định hướng thế giới',
                'Trang trí bề mặt',
                'Giải trí ngắn hạn',
                'Tăng tốc độ di chuyển',
            ],
            correctOptionIndex: 0,
        },
        {
            id: '20',
            prompt: 'Triết học thể hiện khát vọng nào của con người?',
            options: [
                'Tìm kiếm chân lý và tri thức',
                'Tạo ra sự ngẫu nhiên',
                'Chỉ ghi nhớ sự kiện',
                'Lặp lại thói quen',
            ],
            correctOptionIndex: 0,
        },
    ],
};